---
title: "Hansen Data Exploration"
author: "Meghan Bowen"
date: "May 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_packages}

library(tidyverse)
library(raster) ##load and manipulate rasters
library(sf) ##load shapefiles
library(spatstat) ##work with shapefiles
library(tmap)

```


```{r load_rasters}

##load rasters

lossyear <- raster("Hansen_GFC-2018-v1.6_lossyear_00N_080W.tif")

#plot(lossyear)


##what is projection? datum is WGS84
lossyear@crs
```


```{r load_shps}


##selecting "nome" (Name?) & "populacao" (Population?) variables only for now
muni_shp <- read_sf(dsn = 'municipality_shapefiles', layer = "Amazon_Municipios") %>% 
  dplyr::select(populacao)
#shp projection is also WGS84

muni_2010 <- read_sf(dsn = 'municipality_shapefiles', layer = "municipios_2010")

```


```{r compress}

##expand from 0.00025 x 0.00025 by a factor of 10 --> 0.0025 X 0.0025
lossyear_res <- aggregate(lossyear, fact = 10)


#plot both together
plot(lossyear_res)
plot(muni_2010,add=T)


#crop muni to kinda fit this tile?
muni_bounds <- as(extent(-75, -70, -10, -4), 'SpatialPolygons')
crs(muni_bounds) <- crs(muni_2010)

crop_muni <- sf::st_crop(muni_2010, muni_bounds)
```

```{r extract_mask}

##interest raster by muni?
loss_clip <- crop(lossyear_res, extent(muni_shp))

```



```{r tmap}

##test map 1: border of shapefile ontop of raster
test_map <- tm_shape(lossyear_res) +
  tm_raster(title = "Test Map") +
  tm_shape(muni_shp) +
  tm_borders(col = "darkgreen")
  
test_map

##test map 2: "extract by mask" (loss_clip)
##not working?
test2 <- tm_shape(loss_clip) +
  tm_raster(title = "test 2")

test2

```

##General Spatial R Questions:

1. How to get these huge tile rasters down?! even by fact = 10 it took 20 minutes to get it down. Do we even want to get it down?
2. can't use tm_shape with a shapefile with multiple columns? need to filter it to one attribute?
3.


## Research Questions

1. Does 
2.
3.
